name: .NET Core

on:
  pull_request:
    branches: [ master ]

jobs:
  hyperai_units_abstractions:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: |
        dotnet restore Hyperai.Units.Abstractions
        dotnet restore Hyperai.Units.Abstractions.Tests
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore Hyperai.Units.Abstractions
        dotnet build --configuration Release --no-restore Hyperai.Units.Abstractions.Tests
    - name: Test
      run: dotnet test --no-restore --verbosity normal Hyperai.Units.Abstractions.Tests
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: Hyperai.Units.Abstractions/Hyperai.Units.Abstractions.csproj
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{ secrets.PACKAGE_PUSH }}
        INCLUDE_SYMBOLS: true
  hyperai_units_core:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: |
        dotnet restore Hyperai.Units
        dotnet restore Hyperai.Units.Tests
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore Hyperai.Units
        dotnet build --configuration Release --no-restore Hyperai.Units.Tests
    - name: Test
      run: dotnet test --no-restore --verbosity normal Hyperai.Units.Tests
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: Hyperai.Units/Hyperai.Units.csproj
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{ secrets.PACKAGE_PUSH }}
        INCLUDE_SYMBOLS: true